{{- if .Values.mosquitto.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "homebridge.fullname" . }}-mosquitto
  labels:
    {{- include "homebridge.mosquitto.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "homebridge.mosquitto.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "homebridge.mosquitto.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.mosquitto.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      securityContext:
        runAsUser: 1883
        runAsGroup: 1883
        fsGroup: 1883
      containers:
        - name: mosquitto
          image: "{{ .Values.mosquitto.image.repository }}:{{ .Values.mosquitto.image.tag }}"
          imagePullPolicy: {{ .Values.mosquitto.image.pullPolicy }}
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
            - name: data
              mountPath: /mosquitto/data
            - name: log
              mountPath: /mosquitto/log
          {{- with .Values.mosquitto.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "homebridge.fullname" . }}-mosquitto
        - name: data
          {{- if .Values.mosquitto.persistence.enabled }}
          {{- if eq .Values.mosquitto.persistence.type "hostPath" }}
          hostPath:
            path: {{ .Values.mosquitto.persistence.hostPath }}/data
            type: DirectoryOrCreate
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ include "homebridge.fullname" . }}-mosquitto-data
          {{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
        - name: log
          {{- if .Values.mosquitto.persistence.enabled }}
          {{- if eq .Values.mosquitto.persistence.type "hostPath" }}
          hostPath:
            path: {{ .Values.mosquitto.persistence.hostPath }}/log
            type: DirectoryOrCreate
          {{- else }}
          persistentVolumeClaim:
            claimName: {{ include "homebridge.fullname" . }}-mosquitto-log
          {{- end }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
