{{- if and .Values.homebridge.persistence.enabled (eq .Values.homebridge.persistence.type "hostPath") }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "homebridge.fullname" . }}
  labels:
    {{- include "homebridge.labels" . | nindent 4 }}
    app.kubernetes.io/component: homebridge
spec:
  capacity:
    storage: {{ .Values.homebridge.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "homebridge.fullname" . }}
  hostPath:
    path: {{ .Values.homebridge.persistence.hostPath }}
    type: DirectoryOrCreate
{{- end }}
---
{{- if and .Values.mosquitto.enabled .Values.mosquitto.persistence.enabled (eq .Values.mosquitto.persistence.type "hostPath") }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "homebridge.fullname" . }}-mosquitto-data
  labels:
    {{- include "homebridge.mosquitto.labels" . | nindent 4 }}
    app.kubernetes.io/component: mosquitto-data
spec:
  capacity:
    storage: {{ .Values.mosquitto.persistence.dataSize }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "homebridge.fullname" . }}-mosquitto
  hostPath:
    path: {{ .Values.mosquitto.persistence.hostPath }}/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "homebridge.fullname" . }}-mosquitto-log
  labels:
    {{- include "homebridge.mosquitto.labels" . | nindent 4 }}
    app.kubernetes.io/component: mosquitto-log
spec:
  capacity:
    storage: {{ .Values.mosquitto.persistence.logSize }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "homebridge.fullname" . }}-mosquitto
  hostPath:
    path: {{ .Values.mosquitto.persistence.hostPath }}/log
    type: DirectoryOrCreate
{{- end }}
