{{- if .Values.mosquitto.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "homebridge.fullname" . }}-mosquitto
  labels:
    {{- include "homebridge.mosquitto.labels" . | nindent 4 }}
  {{- if .Values.mosquitto.service.loadBalancerIP }}
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ .Values.mosquitto.service.loadBalancerIP }}
    metallb.universe.tf/allow-shared-ip: homebridge
  {{- end }}
spec:
  type: {{ .Values.mosquitto.service.type }}
  ports:
    - port: {{ .Values.mosquitto.service.port }}
      targetPort: mqtt
      protocol: TCP
      name: mqtt
  selector:
    {{- include "homebridge.mosquitto.selectorLabels" . | nindent 4 }}
{{- end }}
