{{- if and .Values.homebridge.enabled .Values.homebridge.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "frontst.fullname" . }}-homebridge
  labels:
    {{- include "frontst.homebridge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.homebridge.service.type }}
  ports:
    - port: {{ .Values.homebridge.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "frontst.homebridge.selectorLabels" . | nindent 4 }}
{{- end }}
