apiVersion: v1
kind: Service
metadata:
  name: {{ include "firefox-remote.fullname" . }}
  labels:
    {{- include "firefox-remote.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: 443
      targetPort: 443
      {{- if and (eq .Values.service.type "NodePort") (.Values.service.nodePort) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
    {{- if .Values.service.vnc.enabled }}
    - name: vnc
      port: {{ .Values.service.vnc.port }}
      targetPort: {{ .Values.service.vnc.port }}
      {{- if and (eq .Values.service.type "NodePort") (.Values.service.vnc.nodePort) }}
      nodePort: {{ .Values.service.vnc.nodePort }}
      {{- end }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "firefox-remote.selectorLabels" . | nindent 4 }}
