{{- if .Values.ingress.tls.selfSigned.enabled }}
{{- $tlsHosts := .Values.ingress.tls.hosts | default (list) }}
{{- if not $tlsHosts }}
{{- $tlsHosts = list }}
{{- range .Values.ingress.hosts }}
{{- $tlsHosts = append $tlsHosts .host }}
{{- end }}
{{- end }}
{{- $secretName := .Values.ingress.tls.secretName | default (printf "%s-tls" (include "firefox-remote.fullname" .)) }}
{{- $cn := first $tlsHosts | default (include "firefox-remote.fullname" .) }}
{{- $days := int (.Values.ingress.tls.selfSigned.validDays | default 365) }}
{{- $cert := genSelfSignedCert $cn nil $tlsHosts $days }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "firefox-remote.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end }}
