{{- if .Values.cncjs.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "xcarve.fullname" . }}-cncjs
  labels:
    {{- include "xcarve.cncjs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cncjs.service.type }}
  ports:
    - port: {{ .Values.cncjs.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "xcarve.cncjs.selectorLabels" . | nindent 4 }}
{{- end }}
