{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "rtl-sdr.fullname" . }}
  labels:
    {{- include "rtl-sdr.labels" . | nindent 4 }}
spec:
  entryPoints:
    - {{ .Values.ingress.entryPoint }}
  routes:
    - match: HostSNI(`*`)
      services:
        - name: {{ include "rtl-sdr.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
