{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rtl-sdr.fullname" . }}
  labels:
    {{- include "rtl-sdr.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: rtl-tcp
      protocol: TCP
      name: rtl-tcp
  selector:
    {{- include "rtl-sdr.selectorLabels" . | nindent 4 }}
{{- end }}
