apiVersion: v1
kind: Service
metadata:
  name: {{ include "iperf3.fullname" . }}-server
  labels:
    {{- include "iperf3.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "iperf3.selectorLabels" . | nindent 4 }}
